### PR TITLE
add new command org-anki-browse-entry

### PR DESCRIPTION
**Pull request by ingtshan**
Use action "guiBrowse" to search note id at anki browser dialog.

This command is useful for me when I find the node entry at my org file, and want to view it at anki quickly.

Of course, if there is any inconvenient, feel free to reject my PR.

### CODE REVIEW

**Comment by eyeinsky** [comment]
Sorry for taking such a long time, I tested this now and I think it works great!

Regarding commenting out the error at the end, the linked issue appears to be fixed https://github.com/FooSoft/anki-connect/issues/277? What version of Anki are you using?

**Comment by ingtshan** [comment]
I update my anki-connect to Supported Anki versions: 2.1.0 (updated 2021-12-27) today,  and test in postman, still get the unreasonable error. (that GUI can find the card but still get error), which you can give a try.

So, still wise to ignore error in "guiBrowse" action I think.

```
{
    "action": "guiBrowse",
    "version": 6,
    "params": {
        "query": "nid:1639194484135"
    }
}

// respond
{
    "result": null,
    "error": "'MockModel' object has no attribute 'cards'"
}
```

**Comment by eyeinsky** [comment]
Right. I'm using Anki version 2.1.15 (on Linux) and I don't get the error. The linked bug also notes that the bug is introduced in 2.1.45 but if you are running version 2.1.0 then this seems to be a different bug (that you could report on anki-connect issue board).

Given that the `org-anki--report-error` doesn't change the execution of a program: it shows the correct note in the gui, even if the response is an error for you, then how about we report the error and you just ignore it (or use a local modified copy of org-anki.el)? If we hide the error like we do now then we won't know if other people are having the same problem.

**Comment by ingtshan** [comment]
Since they fix it in the new version, I have no reason to hid the error, and  It is ok for me to do so. 

And, Happy new year ;-)

**Comment by eyeinsky** [comment]
Thanks! Merged with 400f472e7b2e45502cac2b96bdde33830b84ea60 (needed to make another branch to remove [this line](https://github.com/eyeinsky/org-anki/pull/31/commits/78e81c35399e1b8e7b3145a08ed459fc5087e635#diff-552c81b698a03847a6ec464f5284aa5a5cc98244b1fe5f48ff5513a8bb767b97R579)).

**Pull request closed without merging**
