### PR TITLE
Mitigate #92: error out ASAP for org-anki-import-deck

### PR DESCRIPTION
**Pull request by kenhuang-io**

### CODE REVIEW

**Comment by kenhuang-io** [comment]
Hi @eyeinsky ,

And I have a question for `org-anki--write-note`, I think if there are
more than 2 fields, we should also write them out as in the multiline format,
no matter if the front is multiline or not. Do I understand it right?

**Comment by eyeinsky** [comment]
Merged this here f4737a04a82f8592ef623da40e65881ee5aed718

**Comment by eyeinsky** [comment]
> And I have a question for `org-anki--write-note`, I think if there are more than 2 fields, we should also write them out as in the multiline format, no matter if the front is multiline or not. Do I understand it right?

Could you show me a commit that implements this understanding? I have a vague feeling that the answer is yes.

**Comment by kenhuang-io** [comment]
Sure, here is what I meant:
https://github.com/whatacold/org-anki/commit/0d2616233e090efdea06db824b1910fa1c14a06d

**Pull request closed without merging**
